language: shell

jobs:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.8 IDX=cpu
    - os: linux
      env: TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.8 IDX=cu111
    - os: linux
      env: TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.8 IDX=cu102
    - os: linux
      env: TORCH_VERSION=1.7.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.7 IDX=cpu
    - os: linux
      env: TORCH_VERSION=1.7.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.6 IDX=cu102
    - os: windows
      env: TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.8 IDX=cpu
    - os: osx
      env: TORCH_VERSION=1.8.0 TORCHVISION_VERSION=0.9.0 PYTHON_VERSION=3.8 IDX=cpu

install:
  - source ./.travis/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - source ./.travis/install.sh
  - pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install -q torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install -q torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install -q torch-geometric
  - pip install -q -r requirements.txt

# Build GraphGym
script: python setup.py develop

# Install the codecov pip dependency
install:
  - pip install -q pytest-cov

# Run the unit test
script:
  - pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov

notifications:
  email: false